# Generated by Django 3.1.7 on 2021-04-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='regnum',
            new_name='roll',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rollnum',
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
