# Generated by Django 3.1.7 on 2021-04-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20210430_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
