# Generated by Django 3.1.7 on 2021-04-30 17:38

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_auto_20210430_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, default=django.db.models.fields.NullBooleanField, null=True),
        ),
    ]
